#!/usr/bin/env python3
"""Build data/seed/en_b1.json for CEFR B1 English (unit 1).

Headwords + POS come from the Close-up B1 wordlist (National Geographic
Learning), used only as the *selection* of which words are B1-level. The
French translations are authored here by hand (not copied from the source,
which is English-only). Run: python scripts/build_en_b1_unit1.py
"""

import json
from pathlib import Path

POS_MAP = {
    "n": "noun", "n pl": "noun", "adj": "adjective", "v": "verb",
    "adv": "adverb", "phr v": "phrasal-verb", "phr": "expression",
    "prep": "preposition", "det": "determiner", "conj": "conjunction",
    "prefix": "prefix", "prefix, adj": "adjective", "abbrev": "abbreviation",
    "expr": "expression",
}

# idx -> (headword, source-pos, [french meanings]). POS overrides fix a couple
# of source mislabels (e.g. "fortunately" tagged adj).
UNIT1 = {
    1: ("diving", "n", ["la plongée (sous-marine)"]),
    2: ("festival", "n", ["un festival"]),
    3: ("personal", "adj", ["personnel"]),
    4: ("quality", "n", ["une qualité"]),
    5: ("creative", "adj", ["créatif"]),
    6: ("honest", "adj", ["honnête"]),
    7: ("polite", "adj", ["poli"]),
    8: ("journalist", "n", ["journaliste"]),
    9: ("dress", "v", ["s'habiller"]),
    10: ("pavement", "n", ["le trottoir"]),
    11: ("wave", "v", ["faire signe de la main", "saluer de la main"]),
    12: ("pedestrian", "n", ["un piéton"]),
    13: ("safely", "adv", ["en sécurité", "sans danger"]),
    14: ("seat belt", "n", ["la ceinture de sécurité"]),
    15: ("performance", "n", ["un spectacle", "une représentation"]),
    16: ("film set", "n", ["un plateau de tournage"]),
    17: ("urban", "adj", ["urbain"]),
    18: ("educator", "n", ["un éducateur", "un enseignant"]),
    19: ("spirit", "n", ["l'esprit", "l'état d'esprit"]),
    20: ("positive", "adj", ["positif"]),
    21: ("control", "v", ["contrôler", "maîtriser"]),
    22: ("road safety", "n", ["la sécurité routière"]),
    23: ("part-time", "adj", ["à temps partiel"]),
    24: ("chance", "n", ["une occasion", "une possibilité"]),
    25: ("skill", "n", ["une compétence", "une aptitude"]),
    26: ("community", "n", ["une communauté"]),
    27: ("salary", "n", ["un salaire"]),
    28: ("more importantly", "adv", ["plus important encore", "surtout"]),
    29: ("opportunity", "n", ["une occasion", "une opportunité"]),
    30: ("topic", "n", ["un sujet", "un thème"]),
    31: ("environment", "n", ["l'environnement"]),
    32: ("look out for", "phr v", ["faire attention à", "guetter"]),
    33: ("strap", "n", ["une sangle", "une lanière"]),
    34: ("attach", "v", ["attacher", "joindre (un fichier)"]),
    35: ("film", "v", ["filmer"]),
    36: ("in trouble", "phr", ["en difficulté", "dans le pétrin"]),
    37: ("situation", "n", ["une situation"]),
    38: ("fit in", "phr v", ["s'intégrer", "s'accorder"]),
    39: ("event", "n", ["un événement"]),
    40: ("logical", "adj", ["logique"]),
    41: ("performer", "n", ["un artiste (interprète)"]),
    42: ("suddenly", "adv", ["soudain", "tout à coup"]),
    43: ("programme", "n", ["un programme"]),
    44: ("behave", "v", ["bien se comporter", "bien se tenir"]),
    45: ("persuade", "v", ["persuader", "convaincre"]),
    46: ("personality", "n", ["la personnalité"]),
    47: ("architect", "n", ["un architecte"]),
    48: ("astronaut", "n", ["un astronaute"]),
    49: ("athlete", "n", ["un athlète"]),
    50: ("camera operator", "n", ["un cadreur", "un opérateur de caméra"]),
    51: ("firefighter", "n", ["un pompier"]),
    52: ("hairdresser", "n", ["un coiffeur"]),
    53: ("lawyer", "n", ["un avocat"]),
    54: ("librarian", "n", ["un bibliothécaire"]),
    55: ("politician", "n", ["un homme / une femme politique"]),
    56: ("run", "v", ["diriger", "gérer"]),
    57: ("sportsperson", "n", ["un sportif"]),
    58: ("design", "v", ["concevoir", "dessiner"]),
    59: ("fight", "v", ["se battre", "combattre"]),
    60: ("put out", "phr v", ["éteindre (un feu)"]),
    61: ("space", "n", ["l'espace", "le cosmos"]),
    62: ("law", "n", ["la loi", "le droit"]),
    63: ("care centre", "n", ["un centre de soins (pour personnes âgées)"]),
    64: ("hard-working", "adj", ["travailleur", "assidu"]),
    65: ("jealous", "adj", ["jaloux"]),
    66: ("generous", "adj", ["généreux"]),
    67: ("though", "adv", ["cependant", "pourtant"]),
    68: ("relaxed", "adj", ["détendu"]),
    69: ("nervous", "adj", ["nerveux", "anxieux"]),
    70: ("upset", "v", ["contrarier", "peiner"]),
    71: ("unkind", "adj", ["méchant", "peu aimable"]),
    72: ("shy", "adj", ["timide"]),
    73: ("sociable", "adj", ["sociable"]),
    74: ("quite", "adv", ["assez", "plutôt"]),
    75: ("reliable", "adj", ["fiable"]),
    76: ("calm", "adj", ["calme"]),
    77: ("recently", "adv", ["récemment"]),
    78: ("fortunately", "adv", ["heureusement"]),  # source mislabels as adj
    79: ("annoyed", "adj", ["agacé", "énervé"]),
    80: ("patient", "adj", ["patient"]),
    81: ("anxious", "adj", ["anxieux", "inquiet"]),
    82: ("confident", "adj", ["sûr de soi", "confiant"]),
    83: ("cheerful", "adj", ["joyeux", "gai"]),
    84: ("miserable", "adj", ["malheureux", "triste"]),
    85: ("serious", "adj", ["sérieux"]),
    86: ("career", "n", ["une carrière"]),
    87: ("focus", "n", ["le point central", "le centre d'attention"]),
    88: ("wildlife", "n", ["la faune (et la flore) sauvage"]),
    89: ("equipment", "n", ["l'équipement", "le matériel"]),
    90: ("habit", "n", ["une habitude"]),
    91: ("repeated", "adj", ["répété"]),
    92: ("permanent", "adj", ["permanent"]),
    93: ("scientific", "adj", ["scientifique"]),
    94: ("based on", "phr", ["basé sur", "fondé sur"]),
    95: ("schedule", "n", ["un emploi du temps", "un planning"]),
    96: ("temporary", "adj", ["temporaire"]),
    97: ("annoying", "adj", ["agaçant", "énervant"]),
    98: ("developing", "adj", ["en développement"]),
    99: ("own", "v", ["posséder"]),
    100: ("fire service", "n", ["les pompiers", "le service d'incendie"]),
    101: ("lecture", "n", ["un cours magistral", "une conférence"]),
    102: ("eco", "prefix, adj", ["éco- (écologique)"]),
    103: ("predict", "v", ["prédire", "prévoir"]),
    104: ("mention", "v", ["mentionner"]),
    105: ("response", "n", ["une réponse"]),
    106: ("travelling", "n", ["les voyages"]),
    107: ("get on", "phr v", ["bien s'entendre (avec qn)"]),
    108: ("argue", "v", ["se disputer", "discuter"]),
    109: ("memorise", "v", ["mémoriser", "apprendre par cœur"]),
    110: ("unnatural", "adj", ["anormal", "peu naturel"]),
    111: ("pause", "v", ["faire une pause", "s'interrompre"]),
    112: ("slightly", "adv", ["légèrement", "un peu"]),
    113: ("typical", "adj", ["typique"]),
    114: ("candidate", "n", ["un candidat"]),
    115: ("full-time", "adj", ["à temps plein"]),
    116: ("retired", "adj", ["à la retraite", "retraité"]),
    117: ("qualification", "n", ["un diplôme", "une qualification"]),
    118: ("unemployed", "adj", ["au chômage", "sans emploi"]),
    119: ("apply", "v", ["postuler", "se porter candidat"]),
    120: ("get married", "phr", ["se marier"]),
    121: ("grow up", "phr v", ["grandir", "devenir adulte"]),
    122: ("go out with", "phr v", ["sortir avec (qn)"]),
    123: ("split up", "phr v", ["se séparer", "rompre"]),
    124: ("out of work", "phr", ["sans emploi", "au chômage"]),
    125: ("bring up", "phr v", ["élever (un enfant)"]),
    126: ("advantage", "n", ["un avantage"]),
    127: ("disadvantage", "n", ["un inconvénient", "un désavantage"]),
    128: ("retire", "v", ["prendre sa retraite"]),
    129: ("wedding", "n", ["un mariage (cérémonie)"]),
    130: ("communication", "n", ["la communication"]),
    131: ("colleague", "n", ["un collègue"]),
    132: ("separate", "adj", ["séparé", "distinct"]),
    133: ("item", "n", ["un article", "un objet"]),
    134: ("abstract", "adj", ["abstrait"]),
    135: ("a number of", "det", ["un certain nombre de", "plusieurs"]),
    136: ("colloquial", "adj", ["familier (langage)"]),
    137: ("contraction", "n", ["une contraction", "une forme contractée"]),
    138: ("exclamation mark", "n", ["un point d'exclamation"]),
    139: ("Yours sincerely", "phr", ["« Veuillez agréer mes salutations distinguées »"]),
    140: ("awesome", "adj", ["génial", "impressionnant"]),
    141: ("regards", "n pl", ["salutations", "amitiés"]),
    142: ("fair", "n", ["un salon", "une foire"]),
    143: ("holiday camp", "n", ["une colonie de vacances"]),
    144: ("volunteer", "adj", ["bénévole", "volontaire"]),
    145: ("wonder", "v", ["se demander"]),
    146: ("sign off", "phr v", ["conclure (une lettre / un e-mail)"]),
    147: ("team player", "n", ["une personne qui a l'esprit d'équipe"]),
    148: ("confidence", "n", ["la confiance (en soi)"]),
    149: ("respect", "v", ["respecter", "admirer"]),
    150: ("support", "v", ["soutenir"]),
    151: ("communicate", "v", ["communiquer"]),
    152: ("no way!", "phr", ["pas question !", "impossible !"]),
    153: ("background", "n", ["l'arrière-plan", "le fond"]),
    154: ("research", "n", ["la recherche", "les recherches"]),
    155: ("leader", "n", ["un chef", "un meneur"]),
    156: ("differently", "adv", ["différemment"]),
    157: ("be worth", "phr", ["valoir (la peine)"]),
    158: ("encourage", "v", ["encourager"]),
    159: ("strength", "n", ["une force", "un point fort"]),
    160: ("make your voice heard", "phr", ["faire entendre sa voix"]),
    161: ("rope", "n", ["une corde"]),
    162: ("compass", "n", ["une boussole"]),
    163: ("match", "n", ["une allumette"]),
    164: ("raise money", "phr", ["collecter des fonds", "récolter de l'argent"]),
    165: ("divide", "v", ["diviser", "partager"]),
    166: ("suggestion", "n", ["une suggestion", "une proposition"]),
    167: ("vote", "v", ["voter"]),
    168: ("presenter", "n", ["un présentateur"]),
}


def main() -> None:
    out = []
    for idx, (head, src_pos, fr) in UNIT1.items():
        out.append(
            {
                "unit": 1,
                "idx": idx,
                "head": head,
                "pos": POS_MAP[src_pos],
                "fr": fr,
                "level": "B1",
            }
        )
    dest = Path(__file__).resolve().parent.parent / "data" / "seed" / "en_b1.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=1))
    print(f"wrote {len(out)} entries to {dest}")


if __name__ == "__main__":
    main()
